/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

union _4_authentication_$node;
struct _IO_FILE;
enum _3_super_fancy_encryption_$op;
enum _4_authentication_$op;
struct _2_main__opaque_Node_1;
union _3_super_fancy_encryption_$node;
struct timeval;
extern void signal(int sig , void *func ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
typedef unsigned long size_t;
typedef struct _IO_FILE FILE;
int _2_main__opaque_array[30]  = 
  {      103,      152,      3,      353, 
        124,      5,      428,      348, 
        5,      393,      110,      7, 
        63,      12,      6,      143, 
        488,      89,      468,      103, 
        23,      118,      313,      96, 
        18,      5,      70,      248, 
        89};
void super_fancy_encryption(char const   *input , char *output ) ;
enum _3_super_fancy_encryption_$op {
    _3_super_fancy_encryption__local$result_STA_0$value_LIT_0 = 150,
    _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0 = 179,
    _3_super_fancy_encryption__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 46,
    _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0 = 191,
    _3_super_fancy_encryption__convert_int2char$left_STA_0$result_STA_0 = 184,
    _3_super_fancy_encryption__load_unsigned_long$left_STA_0$result_STA_0 = 1,
    _3_super_fancy_encryption__convert_int2int$left_STA_0$result_STA_0 = 230,
    _3_super_fancy_encryption__store_unsigned_long$right_STA_0$left_STA_1 = 157,
    _3_super_fancy_encryption__branchIfTrue$expr_STA_0$label_LAB_0 = 51,
    _3_super_fancy_encryption__switch$expr_STA_0$max_LIT_0$min_LIT_1$default_LAB_2$jumpTab_LABLST_3 = 186,
    _3_super_fancy_encryption__call$func_LIT_0 = 192,
    _3_super_fancy_encryption__label$label_LAB_0 = 27,
    _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0 = 9,
    _3_super_fancy_encryption__store_int$left_STA_0$right_STA_1 = 18,
    _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0 = 127,
    _3_super_fancy_encryption__convert_char2int$left_STA_0$result_STA_0 = 172,
    _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0 = 11,
    _3_super_fancy_encryption__store_void_star$left_STA_0$right_STA_1 = 5,
    _3_super_fancy_encryption__store_char$right_STA_0$left_STA_1 = 116,
    _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1 = 196,
    _3_super_fancy_encryption__load_char$left_STA_0$result_STA_0 = 213,
    _3_super_fancy_encryption__goto$label_LAB_0 = 4,
    _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0 = 70,
    _3_super_fancy_encryption__returnVoid$ = 155,
    _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 45,
    _3_super_fancy_encryption__Lt_unsigned_long_unsigned_long2int$right_STA_0$result_STA_0$left_STA_1 = 44,
    _3_super_fancy_encryption__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 83
} ;
enum _4_authentication_$op {
    _4_authentication__store_void_star$left_STA_0$right_STA_1 = 50,
    _4_authentication__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 28,
    _4_authentication__store_char$left_STA_0$right_STA_1 = 175,
    _4_authentication__string$result_STA_0$value_LIT_0 = 89,
    _4_authentication__branchIfTrue$expr_STA_0$label_LAB_0 = 239,
    _4_authentication__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 15,
    _4_authentication__load_int$left_STA_0$result_STA_0 = 151,
    _4_authentication__convert_int2char$left_STA_0$result_STA_0 = 129,
    _4_authentication__label$label_LAB_0 = 163,
    _4_authentication__BAnd_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 109,
    _4_authentication__convert_char2int$left_STA_0$result_STA_0 = 118,
    _4_authentication__store_unsigned_long$left_STA_0$right_STA_1 = 235,
    _4_authentication__Lt_unsigned_long_unsigned_long2int$right_STA_0$result_STA_0$left_STA_1 = 167,
    _4_authentication__convert_unsigned_short2int$left_STA_0$result_STA_0 = 13,
    _4_authentication__convert_void_star2void_star$left_STA_0$result_STA_0 = 77,
    _4_authentication__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 228,
    _4_authentication__load_unsigned_short$left_STA_0$result_STA_0 = 132,
    _4_authentication__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 47,
    _4_authentication__constant_void_star$result_STA_0$value_LIT_0 = 225,
    _4_authentication__convert_int2unsigned_long$left_STA_0$result_STA_0 = 87,
    _4_authentication__load_char$left_STA_0$result_STA_0 = 170,
    _4_authentication__local$result_STA_0$value_LIT_0 = 219,
    _4_authentication__store_int$right_STA_0$left_STA_1 = 240,
    _4_authentication__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1 = 128,
    _4_authentication__load_void_star$left_STA_0$result_STA_0 = 112,
    _4_authentication__returnVoid$ = 31,
    _4_authentication__formal$result_STA_0$value_LIT_0 = 221,
    _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0 = 137,
    _4_authentication__goto$label_LAB_0 = 249,
    _4_authentication__constant_int$result_STA_0$value_LIT_0 = 44,
    _4_authentication__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1 = 74,
    _4_authentication__call$func_LIT_0 = 224,
    _4_authentication__load_unsigned_long$left_STA_0$result_STA_0 = 130
} ;
extern double strtod(char const   *str , char const   *endptr ) ;
struct _2_main__opaque_Node_1 {
   int data ;
   struct _2_main__opaque_Node_1 *next ;
};
struct _2_main__opaque_Node_1 *_2_main__opaque_list1_1  =    (struct _2_main__opaque_Node_1 *)0;
extern int fclose(void *stream ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern void abort() ;
void authentication(char *passphrase ) ;
int _1_main_entropy  =    0;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
extern int raise(int sig ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int rand() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) strcmp)(char const   *__s1 ,
                                                                                               char const   *__s2 )  __attribute__((__pure__)) ;
union _4_authentication_$node {
   void *_void_star ;
   unsigned long _unsigned_long ;
   unsigned short _unsigned_short ;
   int _int ;
   char _char ;
};
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
extern  __attribute__((__nothrow__)) unsigned short const   **( __attribute__((__leaf__)) __ctype_b_loc)(void)  __attribute__((__const__)) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
extern int printf(char const   * __restrict  __format  , ...) ;
unsigned char _3_super_fancy_encryption_$array[1][387]  = { {        _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__store_int$left_STA_0$right_STA_1,        _3_super_fancy_encryption__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__store_void_star$left_STA_0$right_STA_1, 
            _3_super_fancy_encryption__call$func_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_unsigned_long$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__store_unsigned_long$right_STA_0$left_STA_1,        _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_unsigned_long$left_STA_0$result_STA_0,        _3_super_fancy_encryption__Lt_unsigned_long_unsigned_long2int$right_STA_0$result_STA_0$left_STA_1, 
            _3_super_fancy_encryption__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)19, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0,        _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__load_char$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__convert_char2int$left_STA_0$result_STA_0,        _3_super_fancy_encryption__convert_int2int$left_STA_0$result_STA_0,        _3_super_fancy_encryption__switch$expr_STA_0$max_LIT_0$min_LIT_1$default_LAB_2$jumpTab_LABLST_3,        (unsigned char)67, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)65, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)147, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)65, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)106, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0,        _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)88,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__convert_int2char$left_STA_0$result_STA_0,        _3_super_fancy_encryption__store_char$right_STA_0$left_STA_1,        _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__goto$label_LAB_0, 
            (unsigned char)154,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0,        _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0,        (unsigned char)89,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__convert_int2char$left_STA_0$result_STA_0,        _3_super_fancy_encryption__store_char$right_STA_0$left_STA_1,        _3_super_fancy_encryption__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)113,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0,        _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0,        _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0,        (unsigned char)90,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__convert_int2char$left_STA_0$result_STA_0,        _3_super_fancy_encryption__store_char$right_STA_0$left_STA_1, 
            _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)72,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0,        _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0,        _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0,        _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0,        _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__load_char$left_STA_0$result_STA_0,        _3_super_fancy_encryption__convert_char2int$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0,        (unsigned char)3,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__convert_int2char$left_STA_0$result_STA_0,        _3_super_fancy_encryption__store_char$right_STA_0$left_STA_1, 
            _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__store_int$left_STA_0$right_STA_1, 
            _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)187,        (unsigned char)254,        (unsigned char)255, 
            (unsigned char)255,        _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)182,        (unsigned char)254, 
            (unsigned char)255,        (unsigned char)255,        _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0,        _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0,        _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__convert_int2char$left_STA_0$result_STA_0, 
            _3_super_fancy_encryption__store_char$right_STA_0$left_STA_1,        _3_super_fancy_encryption__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_super_fancy_encryption__returnVoid$}};
void STRINGS(int n ,
             char str[] ) ;
unsigned char _4_authentication_$array[1][480]  = { {        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__store_int$right_STA_0$left_STA_1,        _4_authentication__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__load_void_star$left_STA_0$result_STA_0,        _4_authentication__convert_void_star2void_star$left_STA_0$result_STA_0,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__store_void_star$left_STA_0$right_STA_1,        _4_authentication__call$func_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__load_unsigned_long$left_STA_0$result_STA_0, 
            _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__store_unsigned_long$left_STA_0$right_STA_1,        _4_authentication__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__load_int$left_STA_0$result_STA_0,        _4_authentication__convert_int2unsigned_long$left_STA_0$result_STA_0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__load_unsigned_long$left_STA_0$result_STA_0, 
            _4_authentication__Lt_unsigned_long_unsigned_long2int$right_STA_0$result_STA_0$left_STA_1,        _4_authentication__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__goto$label_LAB_0, 
            (unsigned char)203,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__load_void_star$left_STA_0$result_STA_0,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)40,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__store_void_star$left_STA_0$right_STA_1,        _4_authentication__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__load_void_star$left_STA_0$result_STA_0, 
            _4_authentication__load_void_star$left_STA_0$result_STA_0,        _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__formal$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__load_void_star$left_STA_0$result_STA_0, 
            _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__load_int$left_STA_0$result_STA_0,        _4_authentication__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _4_authentication__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _4_authentication__load_char$left_STA_0$result_STA_0,        _4_authentication__convert_char2int$left_STA_0$result_STA_0, 
            _4_authentication__convert_int2unsigned_long$left_STA_0$result_STA_0,        _4_authentication__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _4_authentication__load_unsigned_short$left_STA_0$result_STA_0, 
            _4_authentication__convert_unsigned_short2int$left_STA_0$result_STA_0,        _4_authentication__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__BAnd_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _4_authentication__branchIfTrue$expr_STA_0$label_LAB_0, 
            (unsigned char)14,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__call$func_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)56, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__formal$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__load_void_star$left_STA_0$result_STA_0,        _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__load_int$left_STA_0$result_STA_0, 
            _4_authentication__convert_int2unsigned_long$left_STA_0$result_STA_0,        _4_authentication__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _4_authentication__load_char$left_STA_0$result_STA_0, 
            _4_authentication__convert_char2int$left_STA_0$result_STA_0,        _4_authentication__store_int$right_STA_0$left_STA_1,        _4_authentication__call$func_LIT_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)60,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)64,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__load_int$left_STA_0$result_STA_0,        _4_authentication__store_int$right_STA_0$left_STA_1,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)60,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__load_int$left_STA_0$result_STA_0,        _4_authentication__convert_int2char$left_STA_0$result_STA_0,        _4_authentication__formal$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__load_void_star$left_STA_0$result_STA_0, 
            _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__load_int$left_STA_0$result_STA_0,        _4_authentication__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _4_authentication__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _4_authentication__store_char$left_STA_0$right_STA_1,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__load_int$left_STA_0$result_STA_0,        _4_authentication__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _4_authentication__store_int$right_STA_0$left_STA_1,        _4_authentication__goto$label_LAB_0,        (unsigned char)2,        (unsigned char)255, 
            (unsigned char)255,        (unsigned char)255,        _4_authentication__goto$label_LAB_0,        (unsigned char)253, 
            (unsigned char)254,        (unsigned char)255,        (unsigned char)255,        _4_authentication__formal$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__load_void_star$left_STA_0$result_STA_0,        _4_authentication__convert_void_star2void_star$left_STA_0$result_STA_0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)72, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__store_void_star$left_STA_0$right_STA_1, 
            _4_authentication__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _4_authentication__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)88,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)80,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__store_void_star$left_STA_0$right_STA_1,        _4_authentication__call$func_LIT_0,        (unsigned char)5,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)88,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__convert_void_star2void_star$left_STA_0$result_STA_0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)88, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _4_authentication__store_void_star$left_STA_0$right_STA_1, 
            _4_authentication__string$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)96,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__store_void_star$left_STA_0$right_STA_1,        _4_authentication__call$func_LIT_0, 
            (unsigned char)6,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)104,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)108,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__load_int$left_STA_0$result_STA_0,        _4_authentication__store_int$right_STA_0$left_STA_1, 
            _4_authentication__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)104, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _4_authentication__load_int$left_STA_0$result_STA_0, 
            _4_authentication__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _4_authentication__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__goto$label_LAB_0,        (unsigned char)26, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__string$result_STA_0$value_LIT_0, 
            (unsigned char)27,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__convert_void_star2void_star$left_STA_0$result_STA_0,        _4_authentication__local$result_STA_0$value_LIT_0,        (unsigned char)112,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__store_void_star$left_STA_0$right_STA_1,        _4_authentication__call$func_LIT_0, 
            (unsigned char)7,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__goto$label_LAB_0,        (unsigned char)26,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _4_authentication__string$result_STA_0$value_LIT_0,        (unsigned char)54,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__convert_void_star2void_star$left_STA_0$result_STA_0,        _4_authentication__local$result_STA_0$value_LIT_0, 
            (unsigned char)120,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _4_authentication__store_void_star$left_STA_0$right_STA_1,        _4_authentication__call$func_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _4_authentication__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _4_authentication__returnVoid$}};
typedef struct _2_main__opaque_Node_1 *_2_main__opaque_List_1;
int main(int argc , char **argv ) ;
struct _2_main__opaque_Node_1 *_2_main__opaque_list2_1  =    (struct _2_main__opaque_Node_1 *)0;
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1), __leaf__)) strlen)(char const   *__s )  __attribute__((__pure__)) ;
void megaInit(void) ;
char const   *_4_authentication_$strings  =    "JKYSZUWXPACDEGHIMLFRVQOBTN\000Authentication succeeded!\n\000Authentication failed!\n\000";
extern long strtol(char const   *str ,
                   char const   *endptr , int base ) ;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) toupper)(int __c ) ;
union _3_super_fancy_encryption_$node {
   void *_void_star ;
   unsigned long _unsigned_long ;
   int _int ;
   char _char ;
};
char const   *_3_super_fancy_encryption_$strings  =    "";
extern void *malloc(unsigned long size ) ;
extern int scanf(char const   *format  , ...) ;
void STRINGS(int n , char str[] ) 
{ 
  int encodeStrings_i3 ;

  {
  encodeStrings_i3 = 0;
  switch (n) {

  }
}
}
void authentication(char *passphrase ) 
{ 
  char _4_authentication_$locals[1152] ;
  union _4_authentication_$node _4_authentication_$stack[1][32] ;
  union _4_authentication_$node *_4_authentication_$sp[1] ;
  unsigned char *_4_authentication_$pc[1] ;
  unsigned char _4_authentication_$currentOp ;

  {
  _4_authentication_$sp[0] = _4_authentication_$stack[0];
  _4_authentication_$pc[0] = _4_authentication_$array[0];
  while (1) {
    _4_authentication_$currentOp = *(_4_authentication_$pc[0]);
    if (_4_authentication_$currentOp == _4_authentication__convert_int2char$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_char = (char )(_4_authentication_$sp[0] + 0)->_int;
    } else
    if (_4_authentication_$currentOp == _4_authentication__string$result_STA_0$value_LIT_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 1)->_void_star = (void *)(_4_authentication_$strings + *((int *)_4_authentication_$pc[0]));
      (_4_authentication_$sp[0]) ++;
      _4_authentication_$pc[0] += 4;
    } else
    if (_4_authentication_$currentOp == _4_authentication__load_void_star$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_void_star = *((void **)(_4_authentication_$sp[0] + 0)->_void_star);
    } else
    if (_4_authentication_$currentOp == _4_authentication__constant_int$result_STA_0$value_LIT_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 1)->_int = *((int *)_4_authentication_$pc[0]);
      (_4_authentication_$sp[0]) ++;
      _4_authentication_$pc[0] += 4;
    } else
    if (_4_authentication_$currentOp == _4_authentication__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + -1)->_int = (_4_authentication_$sp[0] + 0)->_int == (_4_authentication_$sp[0] + -1)->_int;
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__store_unsigned_long$left_STA_0$right_STA_1) {
      (_4_authentication_$pc[0]) ++;
      *((unsigned long *)(_4_authentication_$sp[0] + 0)->_void_star) = (_4_authentication_$sp[0] + -1)->_unsigned_long;
      _4_authentication_$sp[0] += -2;
    } else
    if (_4_authentication_$currentOp == _4_authentication__load_char$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_char = *((char *)(_4_authentication_$sp[0] + 0)->_void_star);
    } else
    if (_4_authentication_$currentOp == _4_authentication__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + -1)->_int = (_4_authentication_$sp[0] + 0)->_int + (_4_authentication_$sp[0] + -1)->_int;
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__BAnd_int_int2int$right_STA_0$result_STA_0$left_STA_1) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + -1)->_int = (_4_authentication_$sp[0] + -1)->_int & (_4_authentication_$sp[0] + 0)->_int;
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__returnVoid$) {
      (_4_authentication_$pc[0]) ++;
      return;
    } else
    if (_4_authentication_$currentOp == _4_authentication__store_void_star$left_STA_0$right_STA_1) {
      (_4_authentication_$pc[0]) ++;
      *((void **)(_4_authentication_$sp[0] + 0)->_void_star) = (_4_authentication_$sp[0] + -1)->_void_star;
      _4_authentication_$sp[0] += -2;
    } else
    if (_4_authentication_$currentOp == _4_authentication__formal$result_STA_0$value_LIT_0) {
      (_4_authentication_$pc[0]) ++;
      switch (*((int *)_4_authentication_$pc[0])) {
      case 0: 
      (_4_authentication_$sp[0] + 1)->_void_star = (void *)(& passphrase);
      break;
      }
      (_4_authentication_$sp[0]) ++;
      _4_authentication_$pc[0] += 4;
    } else
    if (_4_authentication_$currentOp == _4_authentication__local$result_STA_0$value_LIT_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 1)->_void_star = (void *)(_4_authentication_$locals + *((int *)_4_authentication_$pc[0]));
      (_4_authentication_$sp[0]) ++;
      _4_authentication_$pc[0] += 4;
    } else
    if (_4_authentication_$currentOp == _4_authentication__convert_unsigned_short2int$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_int = (int )(_4_authentication_$sp[0] + 0)->_unsigned_short;
    } else
    if (_4_authentication_$currentOp == _4_authentication__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + -1)->_void_star = (_4_authentication_$sp[0] + 0)->_void_star + (_4_authentication_$sp[0] + -1)->_unsigned_long;
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__label$label_LAB_0) {
      (_4_authentication_$pc[0]) ++;
    } else
    if (_4_authentication_$currentOp == _4_authentication__call$func_LIT_0) {
      (_4_authentication_$pc[0]) ++;
      switch (*((int *)_4_authentication_$pc[0])) {
      case 8: 
      printf(*((char const   * __restrict  *)(_4_authentication_$locals + 1144)));
      break;
      case 2: 
      *((unsigned short const   ***)(_4_authentication_$locals + 48)) = __ctype_b_loc();
      break;
      case 5: 
      super_fancy_encryption(*((char const   **)(_4_authentication_$locals + 72)),
                             *((char **)(_4_authentication_$locals + 80)));
      break;
      case 1: 
      *((unsigned long *)(_4_authentication_$locals + 32)) = strlen(*((char const   **)(_4_authentication_$locals + 16)));
      break;
      case 6: 
      *((int *)(_4_authentication_$locals + 1132)) = strcmp(*((char const   **)(_4_authentication_$locals + 1112)),
                                                            *((char const   **)(_4_authentication_$locals + 1120)));
      break;
      case 3: 
      exit(-1);
      break;
      case 7: 
      printf(*((char const   * __restrict  *)(_4_authentication_$locals + 1136)));
      break;
      case 4: 
      *((int *)(_4_authentication_$locals + 64)) = toupper(*((int *)(_4_authentication_$locals + 56)));
      break;
      }
      _4_authentication_$pc[0] += 4;
    } else
    if (_4_authentication_$currentOp == _4_authentication__convert_void_star2void_star$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_void_star = (_4_authentication_$sp[0] + 0)->_void_star;
    } else
    if (_4_authentication_$currentOp == _4_authentication__convert_int2unsigned_long$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_unsigned_long = (unsigned long )(_4_authentication_$sp[0] + 0)->_int;
    } else
    if (_4_authentication_$currentOp == _4_authentication__convert_char2int$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_int = (int )(_4_authentication_$sp[0] + 0)->_char;
    } else
    if (_4_authentication_$currentOp == _4_authentication__goto$label_LAB_0) {
      (_4_authentication_$pc[0]) ++;
      _4_authentication_$pc[0] += *((int *)_4_authentication_$pc[0]);
    } else
    if (_4_authentication_$currentOp == _4_authentication__load_unsigned_short$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_unsigned_short = *((unsigned short *)(_4_authentication_$sp[0] + 0)->_void_star);
    } else
    if (_4_authentication_$currentOp == _4_authentication__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + -1)->_void_star = (_4_authentication_$sp[0] + 0)->_void_star + (_4_authentication_$sp[0] + -1)->_int;
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__branchIfTrue$expr_STA_0$label_LAB_0) {
      (_4_authentication_$pc[0]) ++;
      if ((_4_authentication_$sp[0] + 0)->_int) {
        _4_authentication_$pc[0] += *((int *)_4_authentication_$pc[0]);
      } else {
        _4_authentication_$pc[0] += 4;
      }
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__load_int$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_int = *((int *)(_4_authentication_$sp[0] + 0)->_void_star);
    } else
    if (_4_authentication_$currentOp == _4_authentication__constant_unsigned_long$result_STA_0$value_LIT_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_4_authentication_$pc[0]);
      (_4_authentication_$sp[0]) ++;
      _4_authentication_$pc[0] += 8;
    } else
    if (_4_authentication_$currentOp == _4_authentication__Lt_unsigned_long_unsigned_long2int$right_STA_0$result_STA_0$left_STA_1) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + -1)->_int = (_4_authentication_$sp[0] + -1)->_unsigned_long < (_4_authentication_$sp[0] + 0)->_unsigned_long;
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__load_unsigned_long$left_STA_0$result_STA_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 0)->_unsigned_long = *((unsigned long *)(_4_authentication_$sp[0] + 0)->_void_star);
    } else
    if (_4_authentication_$currentOp == _4_authentication__constant_void_star$result_STA_0$value_LIT_0) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + 1)->_void_star = *((void **)_4_authentication_$pc[0]);
      (_4_authentication_$sp[0]) ++;
      _4_authentication_$pc[0] += 8;
    } else
    if (_4_authentication_$currentOp == _4_authentication__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + -1)->_void_star = (_4_authentication_$sp[0] + -1)->_void_star + (_4_authentication_$sp[0] + 0)->_unsigned_long;
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__store_int$right_STA_0$left_STA_1) {
      (_4_authentication_$pc[0]) ++;
      *((int *)(_4_authentication_$sp[0] + -1)->_void_star) = (_4_authentication_$sp[0] + 0)->_int;
      _4_authentication_$sp[0] += -2;
    } else
    if (_4_authentication_$currentOp == _4_authentication__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1) {
      (_4_authentication_$pc[0]) ++;
      (_4_authentication_$sp[0] + -1)->_unsigned_long = (_4_authentication_$sp[0] + 0)->_unsigned_long * (_4_authentication_$sp[0] + -1)->_unsigned_long;
      (_4_authentication_$sp[0]) --;
    } else
    if (_4_authentication_$currentOp == _4_authentication__store_char$left_STA_0$right_STA_1) {
      (_4_authentication_$pc[0]) ++;
      *((char *)(_4_authentication_$sp[0] + 0)->_void_star) = (_4_authentication_$sp[0] + -1)->_char;
      _4_authentication_$sp[0] += -2;
    } else {

    }
  }
}
}
void super_fancy_encryption(char const   *input , char *output ) 
{ 
  char _3_super_fancy_encryption_$locals[48] ;
  union _3_super_fancy_encryption_$node _3_super_fancy_encryption_$stack[1][32] ;
  union _3_super_fancy_encryption_$node *_3_super_fancy_encryption_$sp[1] ;
  unsigned char *_3_super_fancy_encryption_$pc[1] ;
  int control13 ;
  int min14 ;
  int max15 ;
  int default16 ;
  unsigned char *jumpTab17 ;

  {
  _3_super_fancy_encryption_$sp[0] = _3_super_fancy_encryption_$stack[0];
  _3_super_fancy_encryption_$pc[0] = _3_super_fancy_encryption_$array[0];
  while (1) {
    switch (*(_3_super_fancy_encryption_$pc[0])) {
    case _3_super_fancy_encryption__returnVoid$: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    return;
    break;
    case _3_super_fancy_encryption__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + -1)->_unsigned_long = (_3_super_fancy_encryption_$sp[0] + -1)->_unsigned_long * (_3_super_fancy_encryption_$sp[0] + 0)->_unsigned_long;
    (_3_super_fancy_encryption_$sp[0]) --;
    break;
    case _3_super_fancy_encryption__store_char$right_STA_0$left_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    *((char *)(_3_super_fancy_encryption_$sp[0] + -1)->_void_star) = (_3_super_fancy_encryption_$sp[0] + 0)->_char;
    _3_super_fancy_encryption_$sp[0] += -2;
    break;
    case _3_super_fancy_encryption__call$func_LIT_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    switch (*((int *)_3_super_fancy_encryption_$pc[0])) {
    case 1: 
    *((unsigned long *)(_3_super_fancy_encryption_$locals + 40)) = strlen(*((char const   **)(_3_super_fancy_encryption_$locals + 24)));
    break;
    }
    _3_super_fancy_encryption_$pc[0] += 4;
    break;
    case _3_super_fancy_encryption__store_unsigned_long$right_STA_0$left_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    *((unsigned long *)(_3_super_fancy_encryption_$sp[0] + -1)->_void_star) = (_3_super_fancy_encryption_$sp[0] + 0)->_unsigned_long;
    _3_super_fancy_encryption_$sp[0] += -2;
    break;
    case _3_super_fancy_encryption__constant_int$result_STA_0$value_LIT_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 1)->_int = *((int *)_3_super_fancy_encryption_$pc[0]);
    (_3_super_fancy_encryption_$sp[0]) ++;
    _3_super_fancy_encryption_$pc[0] += 4;
    break;
    case _3_super_fancy_encryption__convert_char2int$left_STA_0$result_STA_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 0)->_int = (int )(_3_super_fancy_encryption_$sp[0] + 0)->_char;
    break;
    case _3_super_fancy_encryption__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + -1)->_int = (_3_super_fancy_encryption_$sp[0] + -1)->_int + (_3_super_fancy_encryption_$sp[0] + 0)->_int;
    (_3_super_fancy_encryption_$sp[0]) --;
    break;
    case _3_super_fancy_encryption__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_3_super_fancy_encryption_$pc[0]);
    (_3_super_fancy_encryption_$sp[0]) ++;
    _3_super_fancy_encryption_$pc[0] += 8;
    break;
    case _3_super_fancy_encryption__load_char$left_STA_0$result_STA_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 0)->_char = *((char *)(_3_super_fancy_encryption_$sp[0] + 0)->_void_star);
    break;
    case _3_super_fancy_encryption__convert_int2int$left_STA_0$result_STA_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 0)->_int = (_3_super_fancy_encryption_$sp[0] + 0)->_int;
    break;
    case _3_super_fancy_encryption__local$result_STA_0$value_LIT_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 1)->_void_star = (void *)(_3_super_fancy_encryption_$locals + *((int *)_3_super_fancy_encryption_$pc[0]));
    (_3_super_fancy_encryption_$sp[0]) ++;
    _3_super_fancy_encryption_$pc[0] += 4;
    break;
    case _3_super_fancy_encryption__store_void_star$left_STA_0$right_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    *((void **)(_3_super_fancy_encryption_$sp[0] + 0)->_void_star) = (_3_super_fancy_encryption_$sp[0] + -1)->_void_star;
    _3_super_fancy_encryption_$sp[0] += -2;
    break;
    case _3_super_fancy_encryption__load_int$left_STA_0$result_STA_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 0)->_int = *((int *)(_3_super_fancy_encryption_$sp[0] + 0)->_void_star);
    break;
    case _3_super_fancy_encryption__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    if ((_3_super_fancy_encryption_$sp[0] + 0)->_int) {
      _3_super_fancy_encryption_$pc[0] += *((int *)_3_super_fancy_encryption_$pc[0]);
    } else {
      _3_super_fancy_encryption_$pc[0] += 4;
    }
    (_3_super_fancy_encryption_$sp[0]) --;
    break;
    case _3_super_fancy_encryption__load_void_star$left_STA_0$result_STA_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 0)->_void_star = *((void **)(_3_super_fancy_encryption_$sp[0] + 0)->_void_star);
    break;
    case _3_super_fancy_encryption__goto$label_LAB_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    _3_super_fancy_encryption_$pc[0] += *((int *)_3_super_fancy_encryption_$pc[0]);
    break;
    case _3_super_fancy_encryption__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + -1)->_void_star = (_3_super_fancy_encryption_$sp[0] + -1)->_void_star + (_3_super_fancy_encryption_$sp[0] + 0)->_unsigned_long;
    (_3_super_fancy_encryption_$sp[0]) --;
    break;
    case _3_super_fancy_encryption__convert_int2char$left_STA_0$result_STA_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 0)->_char = (char )(_3_super_fancy_encryption_$sp[0] + 0)->_int;
    break;
    case _3_super_fancy_encryption__store_int$left_STA_0$right_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    *((int *)(_3_super_fancy_encryption_$sp[0] + 0)->_void_star) = (_3_super_fancy_encryption_$sp[0] + -1)->_int;
    _3_super_fancy_encryption_$sp[0] += -2;
    break;
    case _3_super_fancy_encryption__formal$result_STA_0$value_LIT_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    switch (*((int *)_3_super_fancy_encryption_$pc[0])) {
    case 1: 
    (_3_super_fancy_encryption_$sp[0] + 1)->_void_star = (void *)(& output);
    break;
    case 0: 
    (_3_super_fancy_encryption_$sp[0] + 1)->_void_star = (void *)(& input);
    break;
    }
    (_3_super_fancy_encryption_$sp[0]) ++;
    _3_super_fancy_encryption_$pc[0] += 4;
    break;
    case _3_super_fancy_encryption__Lt_unsigned_long_unsigned_long2int$right_STA_0$result_STA_0$left_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + -1)->_int = (_3_super_fancy_encryption_$sp[0] + -1)->_unsigned_long < (_3_super_fancy_encryption_$sp[0] + 0)->_unsigned_long;
    (_3_super_fancy_encryption_$sp[0]) --;
    break;
    case _3_super_fancy_encryption__label$label_LAB_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    break;
    case _3_super_fancy_encryption__load_unsigned_long$left_STA_0$result_STA_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 0)->_unsigned_long = *((unsigned long *)(_3_super_fancy_encryption_$sp[0] + 0)->_void_star);
    break;
    case _3_super_fancy_encryption__switch$expr_STA_0$max_LIT_0$min_LIT_1$default_LAB_2$jumpTab_LABLST_3: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    control13 = (_3_super_fancy_encryption_$sp[0] + 0)->_int;
    (_3_super_fancy_encryption_$sp[0]) --;
    min14 = *((int *)(_3_super_fancy_encryption_$pc[0] + 4));
    max15 = *((int *)_3_super_fancy_encryption_$pc[0]);
    default16 = *((int *)(_3_super_fancy_encryption_$pc[0] + 8));
    jumpTab17 = _3_super_fancy_encryption_$pc[0] + 12;
    if (control13 < min14) {
      _3_super_fancy_encryption_$pc[0] += default16;
    } else
    if (control13 > max15) {
      _3_super_fancy_encryption_$pc[0] += default16;
    } else {
      _3_super_fancy_encryption_$pc[0] += *((int *)((char *)jumpTab17 + (control13 - min14) * 4));
    }
    break;
    case _3_super_fancy_encryption__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + -1)->_int = (_3_super_fancy_encryption_$sp[0] + -1)->_int - (_3_super_fancy_encryption_$sp[0] + 0)->_int;
    (_3_super_fancy_encryption_$sp[0]) --;
    break;
    case _3_super_fancy_encryption__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_3_super_fancy_encryption_$pc[0]) ++;
    (_3_super_fancy_encryption_$sp[0] + 0)->_unsigned_long = (unsigned long )(_3_super_fancy_encryption_$sp[0] + 0)->_int;
    break;
    }
  }
}
}
int main(int argc , char **argv ) 
{ 
  int i3 ;
  int r4 ;
  struct _2_main__opaque_Node_1 *p5 ;

  {
  megaInit();
  i3 = 0;
  while (i3 < 2) {
    r4 = rand();
    {
    p5 = (struct _2_main__opaque_Node_1 *)malloc(sizeof(struct _2_main__opaque_Node_1 ));
    if (p5 != (struct _2_main__opaque_Node_1 *)0UL) {
      p5->data = r4;
      if (_2_main__opaque_list1_1 != (struct _2_main__opaque_Node_1 *)0UL) {
        p5->next = _2_main__opaque_list1_1->next;
        _2_main__opaque_list1_1->next = p5;
      } else {
        p5->next = p5;
        _2_main__opaque_list1_1 = p5;
      }
    } else {

    }
    }
    i3 ++;
  }
  _2_main__opaque_list2_1 = _2_main__opaque_list1_1;
  _1_main_entropy = (int )((unsigned long )argv) + _1_main_entropy;
  _1_main_entropy = argc >> _1_main_entropy;
  if (argc != 2) {
    printf((char const   */* __restrict  */)"Please give one argument.\n");
    exit(-1);
  }
  authentication(*(argv + 1));
  return (0);
}
}
void megaInit(void) 
{ 


  {

}
}
